<?php

function form_example_person() {
  $items = array();

  $items['person/form-person'] = array( //this creates a URL that will call this form at "person/form_person"
    'title' => 'Person Details Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'file' => 'form_person.inc',
    'page arguments' => array('form_details_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}